# This file extends the Astro docker-compose setup with additional services
# It will be automatically loaded by docker-compose when running astro dev start

services:

  minio:
    image: minio/minio
    container_name: minio
    platform: linux/arm64
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - airflow
      - default

    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'mlflow']
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped  

  
  # MLflow tracking server
  mlflow:
    image: python:3.12.0
    platform: linux/arm64
    command: >
      bash -c
              "pip install mlflow==2.9.2 psycopg2-binary boto3 && 
               export MLFLOW_S3_ENDPOINT_URL=http://minio:9000 &&
               mlflow server --host 0.0.0.0 --port 5001 
               --backend-store-uri postgresql://mlflow:mlflow@mlflow-db:5432/mlflow 
               --default-artifact-root s3://mlflow-artifacts/ 
               --serve-artifacts"
    ports:
      - '5001:5001'
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - mlflow-db
      - minio
    networks:
      - airflow
      - default
    restart: unless-stopped

  # PostgreSQL for MLflow
  mlflow-db:
    image: postgres:16-alpine
    platform: linux/arm64
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - mlflow-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'mlflow']
      interval: 5s
      retries: 5
    networks:
      - airflow
      - default
    restart: unless-stopped

volumes:
  minio-data:
  mlflow-db-volume:

networks:
  airflow:
    external: true
    name: sales-forecasting-pipeline_868451_airflow
  default:
    name: sales-forecasting-pipeline_868451_default    